name = lernwelt_gluehpilz
title = Lernwelt: Gluehpilz-Wald
description = Markenfreies Lernwelt-Thema: ein gemuetliches Pilzreich als ideale Erstwelt. Bunte Gluehpilze, Pilzwald, Glueh-Hoehle und Bach, Tag-Nacht-Wechsel ueber leuchtende Pilze, Wald-Tagebuch, rettbare Waldtiere, Leucht-Kaefer zum Reiten, grosses Pilzhaus, Raenge und Abzeichen - baut auf der lernwelt-Engine auf. Sehr niederschwellig. Startausruestung beim ersten Join zum schnellen Testen.
depends = lernwelt
optional_depends = mobs, mcl_mobs
